import { devmapHtml } from "../src/devmap_page.js";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { execFileSync } from "node:child_process";
let pass = 0, fail = 0;
const ok = (c, m) => { if (c) { pass++; console.log("  ok - " + m); } else { fail++; console.log("  FAIL - " + m); } };
const html = devmapHtml("k", { NAJ_NAV_CSS: "", NAJ_FONTS: "", najNav: () => "" });
const js = html.split("<script>").pop().split("</script>")[0];
const f = path.join(os.tmpdir(), "v336_page.js"); fs.writeFileSync(f, js);
let parsed = true; try { execFileSync(process.execPath, ["--check", f], { stdio: "pipe" }); } catch (e) { parsed = false; }
ok(parsed, "the page script parses");
ok(/function dimOf\(s\)\{[^\n]*S\.prof\|\|S\.fdev/.test(js), "a profile dims the other areas");
ok(js.includes("data-b=") && js.includes("Show all price bands"), "price bands are toggles with a show-all state");
ok(js.includes("class=prow") && js.includes("select(r.getAttribute"), "profile rows select the area");
ok(js.includes("<details class=evd") && js.includes("caret-down"), "positioning evidence is collapsible with a chevron icon");
ok(js.includes("lg.id=\"maplg\"") && js.includes("function mapLegend"), "legend overlay on the map");
ok(js.includes("dlink evc peer"), "peers are cards that open the profile");
ok(js.includes("class=dvg") && js.includes("class=pjg") && js.includes("dir=auto"), "developer and project lists are card grids; names use dir=auto");
ok(js.includes("function pjCard") && js.includes("/img/blocks_") && js.includes("Project details") && js.includes("pj-fill"), "project cards place on the map from the district footprints; unplaced say so");
ok(js.includes("function rowGo") && js.includes('addEventListener("click",rowGo)') && !js.includes("r.onclick=go"), "price-by-area rows use one delegated click handler per panel");
ok(js.includes("if(!dvp||!dvt||!dvo||!cs||!co)return") && js.includes("function safeWire") && js.includes("function dedupeIds"), "a profile open cannot throw in wireDetail; duplicate ids are renamed in the hidden copy");
ok(!js.includes("'Mostly '") && !/Mostly [^<]{0,12}band/.test(js), "no developer tag says Mostly + band any more");
ok(js.includes("Most sales") && /function tagText[^\n]*[^\n]*\n[^\n]*fmt\(pu\(x\)\)/.test(js) && js.includes("pul()+'</small>'"), "the tag states the measured range in the unit the page shows (pu/pul follow the toggle)");
ok(!/function tagText[\s\S]{0,700}(budget|luxury|premium)/i.test(js.replace("Ultra-luxury","")), "the new tag does not use budget, luxury or premium");
ok(html.includes(".pk>.tag{order:3;flex:0 0 100%;min-width:110px") && html.includes("white-space:nowrap") && /\.pk\{display:flex;flex-wrap:wrap/.test(html), "a developer tag sits on its own full-width line with a min-width and cannot wrap mid-word");
ok(js.includes("function devHead") && js.includes("class=dvtile") && js.includes("class=dvcg") && js.includes("No developer with 3+ sales sits here") && js.includes("About these numbers"), "area panel: developer count tile, first cards, quiet no-developer card, About these numbers");
ok(js.includes("lim=S.devAll?all.length:6") && js.includes("Show all '+all.length+' developers"), "first six developers as cards with a Show all button");
ok(js.includes("where the developer is not recorded yet"), "the unrecorded-sales sentence is kept (in About these numbers)");
ok(/function devHead\(st,area,thin\)\{\s*var all=\[\];st\.tiers/.test(js) && !/function devHead[^\n]*view\./.test(js), "tile and cards are built from all developers (st), so the only-my-developers filter cannot change them");
ok(js.includes("<span class=inl>") && js.includes("in your list") && js.includes("none of them in your list"), "a card shows an in your list chip only for list members; the tile says when none are");
ok(js.includes("the price bands below are filtered to your list") && !js.includes("hidden by your filter"), "the confusing hidden-by-your-filter box is replaced by one quiet note");
ok(js.includes("function clipName") && html.includes("a.dvc.dlink{text-decoration:none}") && js.includes("function panelTop"), "long names clipped, card has no link underline, panel scrolls to its top on select");
console.log("\n" + pass + " passed, " + fail + " failed"); process.exit(fail ? 1 : 0);
