// v376 - writes src/investor_config.generated.js from config/investor_segments.json and config/investor_presets.json (the Worker bundle cannot read files).
// Edit the JSON, run: node scripts/build_investor_config.mjs . A test fails if the generated module and the JSON drift apart.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
export function generated() {
  const seg = JSON.parse(fs.readFileSync(path.join(ROOT, "config", "investor_segments.json"), "utf8"));
  const pre = JSON.parse(fs.readFileSync(path.join(ROOT, "config", "investor_presets.json"), "utf8"));
  const sta = JSON.parse(fs.readFileSync(path.join(ROOT, "config", "investor_stats.json"), "utf8"));
  return "// GENERATED by scripts/build_investor_config.mjs from config/investor_*.json - do not edit by hand.\n" +
    "export const SEGMENTS_CONFIG = " + JSON.stringify(seg, null, 1) + ";\nexport const PRESETS_CONFIG = " + JSON.stringify(pre, null, 1) + ";\nexport const STATS_CONFIG = " + JSON.stringify(sta, null, 1) + ";\n";
}
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  fs.writeFileSync(path.join(ROOT, "src", "investor_config.generated.js"), generated());
  console.log("wrote src/investor_config.generated.js");
}
