// v414 - generate src/dev_claims_data.js from data/developer_claims/*.json (the worker bundles JS, not JSON files). Re-run after editing a claims file; test/test_v414_*.mjs fails if the two differ.
//   node scripts/gen_dev_claims_js.mjs          write src/dev_claims_data.js
//   node scripts/gen_dev_claims_js.mjs --check  exit 1 when the file on disk is not what the claims files give
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
export function generate() {
  const dir = path.join(ROOT, "data", "developer_claims"), out = {};
  for (const f of fs.readdirSync(dir).filter((x) => x.endsWith(".json")).sort()) {
    const j = JSON.parse(fs.readFileSync(path.join(dir, f), "utf8"));
    if (!j.key) continue;
    delete j._about;
    out[j.key] = j;
  }
  return "// GENERATED by scripts/gen_dev_claims_js.mjs from data/developer_claims/*.json - do not edit by hand.\nexport const DEV_CLAIMS = " + JSON.stringify(out, null, 1) + ";\n";
}
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const target = path.join(ROOT, "src", "dev_claims_data.js"), txt = generate();
  if (process.argv.includes("--check")) { const cur = fs.existsSync(target) ? fs.readFileSync(target, "utf8") : ""; process.exit(cur.replace(/\r\n/g, "\n") === txt ? 0 : 1); }
  fs.writeFileSync(target, txt);
  console.log("wrote " + target + " (" + txt.length + " bytes)");
}
