// Bundles the Momo page images (assets/fit/*.jpg and *.png: the logo, the page icon, the photos; credits in assets/fit/CREDITS.md) into src/fit_img.js as base64 strings,
// so the worker serves them itself (owner only, /fit_img/<name>.jpg) and the page makes no request to any third party.
// Run after changing a photo:   node scripts/gen_fit_img.mjs
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const DIR = path.join(ROOT, "assets", "fit");
const names = fs.readdirSync(DIR).filter((f) => /\.(jpg|png)$/.test(f)).sort();
let out = "// GENERATED by scripts/gen_fit_img.mjs from assets/fit/*.jpg|png - do not edit. Photos: Pexels licence, see assets/fit/CREDITS.md\n";
out += "export const FIT_IMG = {\n";
let total = 0; const types = {};
for (const f of names) {
  const buf = fs.readFileSync(path.join(DIR, f));
  const png = f.endsWith(".png"), name = f.replace(/\.(jpg|png)$/, "");
  if (png ? !(buf[0] === 0x89 && buf[1] === 0x50) : !(buf[0] === 0xff && buf[1] === 0xd8)) throw new Error(f + " is not a real " + (png ? "PNG" : "JPEG"));
  total += buf.length; types[name] = png ? "image/png" : "image/jpeg";
  out += "  " + JSON.stringify(name) + ": " + JSON.stringify(buf.toString("base64")) + ",\n";
}
out += "};\nexport const FIT_IMG_TYPE = " + JSON.stringify(types) + ";\n";
fs.writeFileSync(path.join(ROOT, "src", "fit_img.js"), out);
console.log(names.length + " images, " + total + " bytes -> src/fit_img.js (" + out.length + " chars)");
