// Writes src/devmap_dm.js: the Developers-map logic (src/devmap_core.js, a text block the browser page evaluates) as REAL module code, so the
// Worker (which forbids eval) can use the very same functions for the PDFs. test/test_v324_area_pdf.mjs fails if the two ever differ.
//   node scripts/gen_devmap_dm.mjs
import fs from "node:fs";
import { DEVMAP_CORE_JS } from "../src/devmap_core.js";
const head = "// GENERATED by scripts/gen_devmap_dm.mjs from src/devmap_core.js (v324). Do not edit by hand: edit devmap_core.js and run the script.\n// It is the same text the browser page runs, as real module code (the Worker cannot evaluate text).\n";
fs.writeFileSync(new URL("../src/devmap_dm.js", import.meta.url), head + DEVMAP_CORE_JS + "\nexport { DM };\n");
console.log("wrote src/devmap_dm.js");
