// Bundles the FIT page photos (assets/fit/*.jpg, credits in assets/fit/CREDITS.md) into src/fit_img.js as base64 strings,
// so the worker serves them itself (owner only, /fit_img/<name>.jpg) and the page makes no request to any third party.
// Run after changing a photo:   node scripts/gen_fit_img.mjs
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const DIR = path.join(ROOT, "assets", "fit");
const names = fs.readdirSync(DIR).filter((f) => f.endsWith(".jpg")).sort();
let out = "// GENERATED by scripts/gen_fit_img.mjs from assets/fit/*.jpg - do not edit. Photos: Pexels licence, see assets/fit/CREDITS.md\n";
out += "export const FIT_IMG = {\n";
let total = 0;
for (const f of names) {
  const buf = fs.readFileSync(path.join(DIR, f));
  if (buf[0] !== 0xff || buf[1] !== 0xd8) throw new Error(f + " is not a JPEG");
  total += buf.length;
  out += "  " + JSON.stringify(f.replace(/\.jpg$/, "")) + ": " + JSON.stringify(buf.toString("base64")) + ",\n";
}
out += "};\n";
fs.writeFileSync(path.join(ROOT, "src", "fit_img.js"), out);
console.log(names.length + " photos, " + total + " bytes -> src/fit_img.js (" + out.length + " chars)");
