// DEVELOPER CROSSWALK - runtime lookup (pure, no I/O, no eval; safe in a worker). Kendall, 4 Oct 2026: "this cannot happen again".
//   canonicalOf(name)  -> canonical developer id ("damac", "nakheel", "zaya" ...) or, for a developer with no curated brand, a
//                         deterministic slug of its own normalised name; "" for an empty name. Never fuzzy.
//   aliasesOf(id)      -> the registered company names (English and Arabic) recorded for that id, [] if none.
//   displayOf(id)      -> display name ("DAMAC") or null for an uncurated id.
//   resolve(name, kind)-> {id, how, confidence}; kind "project" also reads project-name tokens (confidence 0.8).
// The rules live in src/devcross_data.js, GENERATED by naj-market-pulse/scripts/build_developer_crosswalk.py from the register,
// DLD projects, Ejari index, Brief sheets and unit-mix cards. norm() below MIRRORS the Python norm(); the parity vectors in the data
// are checked by test/test_devcross.mjs, so the two cannot drift silently.
import { DEVCROSS_DATA as D } from "./devcross_data.js";

const AR_FOLD = { "أ": "ا", "إ": "ا", "آ": "ا", "ٱ": "ا", "ى": "ي", "ة": "ه", "ؤ": "و", "ئ": "ي" };
const LEGAL = new Set(("llc lc pjsc psc jsc fze fzc fzco fz dmcc dwc ltd limited co company inc soc branch the " +
  "شذمم ذمم شمع شمخ شمح ممح ششو شركه فرع مساهمه عامه ذات مسووليه محدوده منطقه حره").split(" "));

export function norm(s) {
  s = String(s == null ? "" : s).normalize("NFKC").toLowerCase();
  s = s.replace(/[ً-ْـ]/g, "");
  s = Array.from(s).map((ch) => AR_FOLD[ch] || ch).join("");
  s = s.replace(/\bowned by\b.*$/, " ").replace(/\bone person company\b/g, " ");
  s = s.replace(/[^a-z0-9ء-ي]+/g, " ").trim();
  const t = s ? s.split(" ") : [], out = [], run = [];
  const flush = () => { if (run.length >= 2) out.push(run.join("")); else out.push(...run); run.length = 0; };
  for (const w of t) { if (w.length === 1 && !/\d/.test(w)) run.push(w); else { flush(); out.push(w); } }
  flush();
  return out.filter((w) => !LEGAL.has(w)).join(" ");
}

const BR = D.brands.map((b) => ({
  id: b.id, display: b.display, exact: b.exact, aliases: b.aliases,
  start: b.start.map((x) => x.split(" ")), has: b.has.map((x) => x.split(" ")), proj: b.proj.map((x) => x.split(" ")),
}));
const BY_ID = Object.fromEntries(BR.map((b) => [b.id, b]));
const hasSeq = (toks, seq) => { const n = seq.length; for (let i = 0; i + n <= toks.length; i++) { let ok = true; for (let j = 0; j < n; j++) if (toks[i + j] !== seq[j]) { ok = false; break; } if (ok) return true; } return false; };

export function resolve(name, kind) {
  const key = norm(name);
  if (!key) return { id: "", how: "empty", confidence: 0 };
  const toks = key.split(" ");
  for (const b of BR) if (Object.prototype.hasOwnProperty.call(b.exact, key)) return { id: b.id, how: "exact_alias", confidence: b.exact[key] };
  for (const b of BR) {
    for (const s of b.start) if (s.length <= toks.length && s.every((w, i) => toks[i] === w)) return { id: b.id, how: "start_rule", confidence: 1 };
    for (const s of b.has) if (hasSeq(toks, s)) return { id: b.id, how: "has_rule", confidence: 0.95 };
  }
  if (kind === "project") for (const b of BR) for (const s of b.proj) if (hasSeq(toks, s)) return { id: b.id, how: "project_token", confidence: 0.8 };
  return { id: key.replace(/ /g, "-"), how: "singleton", confidence: 1 };
}

export const canonicalOf = (name, kind) => resolve(name, kind).id;
export const aliasesOf = (id) => (BY_ID[id] ? BY_ID[id].aliases.slice() : []);
export const displayOf = (id) => (BY_ID[id] ? BY_ID[id].display : null);
export const isCurated = (id) => !!BY_ID[id];
export const DEVCROSS_PARITY = D.parity;
