// GENERATED by scripts/gen_devmap_dm.mjs from src/devmap_core.js (v324). Do not edit by hand: edit devmap_core.js and run the script.
// It is the same text the browser page runs, as real module code (the Worker cannot evaluate text).

var DM=(function(){
var SQFT=10.7639, EVIDENCE_MIN=3;
var TIER_IDS=["ultra","luxury","premium","budget"];
var TIER_NAMES=["Top band","Upper band","Middle band","Entry band"];   // v321 - these name PRICE BANDS (they describe homes, from all Dubai settled sales). Developer positioning has its own words: POSITION_WORDS
// THE ONE CONFIG OBJECT for the four tiers. bounds = the three lower edges in AED per sq m: [ultra-luxury from, luxury from,
// premium from]; below the last is the Entry band. null = the Dubai-wide percentile bands the index carries (p50 / p80 / p95 of settled
// sales by price per sq m). Kendall: set bounds to [a,b,c] to use your own.
var TIER_CFG={bounds:[32292,22604,16684], percentiles:[95,80,50]}; // 4 Oct 2026, Kendall: value-weighted bounds, each tier about a quarter of the money: AED 3,000 / 2,100 / 1,550 per sq ft
var TYPICAL_SQFT=[["Studio",401],["1-bed",779],["2-bed",1248],["3-bed",1848]]; // median Dubai sizes in the sales register, last 12 months
function sqftOf(m){return m==null?null:m/SQFT}
function round(x){return x==null?null:Math.round(x)}
function wquant(pairs,p){ // pairs [[value,weight]]; weighted quantile, p 0..1
  var a=[],tw=0,i;for(i=0;i<pairs.length;i++){var v=pairs[i][0],w=pairs[i][1];if(v!=null&&w>0&&isFinite(v)){a.push([v,w]);tw+=w}}
  if(!a.length)return null;a.sort(function(x,y){return x[0]-y[0]});
  var t=tw*p,c=0;for(i=0;i<a.length;i++){c+=a[i][1];if(c>=t)return a[i][0]}return a[a.length-1][0]}
function wmedian(pairs){return wquant(pairs,0.5)}
function nOf(cells){var n=0;for(var i=0;i<cells.length;i++)n+=cells[i][0];return n}
function pooled(cells,idx){var p=[];for(var i=0;i<cells.length;i++)p.push([cells[i][idx==null?1:idx],cells[i][0]]);return p}
function boundsOf(index,cfg){cfg=cfg||TIER_CFG;if(cfg.bounds&&cfg.bounds.length===3)return cfg.bounds;return (index&&index.cuts&&index.cuts.bounds)||null}
function tierOf(ppsm,bounds){if(ppsm==null||!bounds)return -1;return ppsm>=bounds[0]?0:ppsm>=bounds[1]?1:ppsm>=bounds[2]?2:3}
function bandSay(t,bounds){ // the tier's price band, per sq m and per sq ft
  var lo=t===0?bounds[0]:t===1?bounds[1]:t===2?bounds[2]:null,hi=t===0?null:t===1?bounds[0]:t===2?bounds[1]:bounds[2];
  function f(x){return Math.round(x).toLocaleString("en-US")}
  var m=lo==null?"under AED "+f(hi):hi==null?"AED "+f(lo)+" and above":"AED "+f(lo)+" to "+f(hi);
  var s=lo==null?"under AED "+f(hi/SQFT):hi==null?"AED "+f(lo/SQFT)+" and above":"AED "+f(lo/SQFT)+" to "+f(hi/SQFT);
  return m+" per sq m ("+s+" per sq ft)"}
// a developer's name key: one developer however the register spells it
function devKey(s){var t=String(s==null?"":s).toLowerCase().replace(/[.,&]/g," ").replace(/\b(l l c|llc|fz|fzc|fze|ltd|limited|co|the|real estate|properties|property|developments?|developers?|investments?|group|holding|holdings|company|est)\b/g," ").replace(/\s+/g," ").trim();return t}
function money(x){return x>=1e6?"AED "+(Math.round(x/1e4)/100).toFixed(2)+"m":"AED "+Math.round(x/1e3).toLocaleString("en-US")+"k"}
// the TOTAL PURCHASE PRICE of a typical home at the floor of a tier's per sq m band (Entry band: under the Middle band floor)
function tierPrices(t,bounds){if(!bounds)return "";
  var edge=t===0?bounds[0]:t===1?bounds[1]:bounds[2],i,o=[];
  for(i=0;i<TYPICAL_SQFT.length;i++)o.push(TYPICAL_SQFT[i][0]+" "+(t===3?"under ":"from ")+money(edge*TYPICAL_SQFT[i][1]/SQFT));
  return o.join(" · ")}
// v314 - the tier header as DATA, not a paragraph: the band edges (per sq m), four price cards (label + "from AED 842k" / "under AED 622k") and the Dubai-wide shares
function tierCards(t,bounds){if(!bounds)return [];var edge=t===0?bounds[0]:t===1?bounds[1]:bounds[2],i,o=[];
  for(i=0;i<TYPICAL_SQFT.length;i++)o.push([TYPICAL_SQFT[i][0],(t===3?"under ":"from ")+money(edge*TYPICAL_SQFT[i][1]/SQFT)]);
  return o}
function tierEdges(t,b){return b?{lo:t===0?b[0]:t===1?b[1]:t===2?b[2]:null,hi:t===0?null:t===1?b[0]:t===2?b[1]:b[2]}:null}
function tierShares(t,index){var s=index&&index.cuts&&index.cuts.shares;return s?{n:s.n[t],money:s.money[t]}:null}
function tierShare(t,index){var s=index&&index.cuts&&index.cuts.shares;if(!s)return "";
  return "Dubai-wide: "+s.n[t]+"% of buyers, "+s.money[t]+"% of the money"}
// ---- one developer in one area ----
function devStats(d,bounds){
  var c=d.c||[],n=nOf(c),out={k:d.k,name:d.n,homes:d.h||0,n:n,enough:n>=EVIDENCE_MIN,median:null,medianSqft:null,tier:-1,tierN:[0,0,0,0],tierShare:[0,0,0,0],second:null,aed:null};
  if(!out.enough)return out;
  out.median=round(wmedian(pooled(c,1)));out.medianSqft=round(sqftOf(out.median));out.aed=round(wmedian(pooled(c,2)));
  for(var i=0;i<c.length;i++){var t=tierOf(c[i][1],bounds);if(t>=0)out.tierN[t]+=c[i][0]}
  var tot=out.tierN[0]+out.tierN[1]+out.tierN[2]+out.tierN[3],best=0,i2;
  for(i2=0;i2<4;i2++){out.tierShare[i2]=tot?Math.round(100*out.tierN[i2]/tot):0;if(out.tierN[i2]>out.tierN[best])best=i2}
  out.tier=best; // the rule: the tier where most of its sales in this area fall
  var sec=-1;for(i2=0;i2<4;i2++)if(i2!==best&&out.tierN[i2]>0&&(sec<0||out.tierN[i2]>out.tierN[sec]))sec=i2;
  if(sec>=0&&out.tierShare[sec]>=20)out.second={tier:sec,share:out.tierShare[sec]};
  return out}
// ---- one area: the four tiers, each with its developers ----
function areaStats(area,index,cfg){
  var bounds=boundsOf(index,cfg),devs=area.devs||{},k,all=[],list=[],unknown=null;
  for(k in devs){var d=devs[k];all=all.concat(d.c||[]);if(k==="_"){unknown={n:nOf(d.c||[])};continue}list.push(devStats({k:k,n:d.n,h:d.h,c:d.c},bounds))}
  var n=nOf(all),res={name:area.name,n:n,enough:n>=EVIDENCE_MIN,median:null,medianSqft:null,q1:null,q3:null,bounds:bounds,tiers:[],mixN:[0,0,0,0],mixValue:[0,0,0,0],unknown:unknown,notEnough:[],devCount:list.length,as_of:index&&index.as_of};
  if(res.enough){var p=pooled(all,1);res.median=round(wquant(p,0.5));res.medianSqft=round(sqftOf(res.median));res.q1=round(wquant(p,0.25));res.q3=round(wquant(p,0.75))}
  var vt=0,nt=0,i;
  for(i=0;i<all.length;i++){var t=tierOf(all[i][1],bounds);if(t>=0){res.mixN[t]+=all[i][0];res.mixValue[t]+=all[i][0]*(all[i][2]||0);nt+=all[i][0];vt+=all[i][0]*(all[i][2]||0)}}
  res.unknownTier=[0,0,0,0];if(devs._)for(i=0;i<(devs._.c||[]).length;i++){var tu=tierOf(devs._.c[i][1],bounds);if(tu>=0)res.unknownTier[tu]+=devs._.c[i][0]}   // v314 - sales per tier with no developer recorded
  for(i=0;i<4;i++){res.mixN[i]=nt?Math.round(100*res.mixN[i]/nt):0;res.mixValue[i]=vt?Math.round(100*res.mixValue[i]/vt):0}
  for(i=0;i<4;i++){res.tiers.push({tier:i,id:TIER_IDS[i],name:TIER_NAMES[i],band:bounds?bandSay(i,bounds):"",prices:tierPrices(i,bounds),share:tierShare(i,index),cards:tierCards(i,bounds),edges:tierEdges(i,bounds),shares:tierShares(i,index),devs:[],median:null,medianSqft:null})}
  for(i=0;i<list.length;i++){var s=list[i];if(!s.enough){res.notEnough.push(s);continue}res.tiers[s.tier].devs.push(s)}
  for(i=0;i<4;i++){var tr=res.tiers[i];tr.devs.sort(function(a,b){return b.n-a.n||(b.median-a.median)});tr.nDevs=tr.devs.length;
    var cells=[];for(var j=0;j<tr.devs.length;j++)cells=cells.concat(devs[tr.devs[j].k].c||[]);
    if(tr.devs.length){tr.median=round(wmedian(pooled(cells,1)));tr.medianSqft=round(sqftOf(tr.median))}}
  return res}
// ---- the realtor's shortlist: keep only these developer keys ----
function shortlistFilter(stats,set,area){var o=JSON.parse(JSON.stringify(stats)),i,j;
  function keep(d){return !!set[d.k]}
  for(i=0;i<o.tiers.length;i++){var tr=o.tiers[i];tr.devs=tr.devs.filter(keep);tr.nDevs=tr.devs.length;tr.median=null;tr.medianSqft=null;
    if(area&&tr.devs.length){var cells=[];for(j=0;j<tr.devs.length;j++)cells=cells.concat(area.devs[tr.devs[j].k].c||[]);tr.median=round(wmedian(pooled(cells,1)));tr.medianSqft=round(sqftOf(tr.median))}}
  o.notEnough=o.notEnough.filter(keep);return o}
// ---- the client's budget. q: {mode:"sqft"|"sqm"|"total", min, max, beds}. Drops developers out of range. ----
function budgetFit(devEntry,stat,q,bounds){
  if(!stat.enough)return {fit:null,why:"not enough sales (under "+EVIDENCE_MIN+")"};
  if(q.mode==="total"){
    var cells=(devEntry.c||[]).filter(function(c){return q.beds==null||c[3]===q.beds}),n=nOf(cells);
    if(n<EVIDENCE_MIN)return {fit:null,why:"not enough sales of this size (under "+EVIDENCE_MIN+")"};
    var m=round(wmedian(pooled(cells,2)));
    return {fit:(q.max==null||m<=q.max)&&(q.min==null||m>=q.min),median:m,n:n,basis:"total"}}
  var v=q.mode==="sqm"?stat.median:stat.medianSqft;
  return {fit:(q.max==null||v<=q.max)&&(q.min==null||v>=q.min),median:v,n:stat.n,basis:q.mode}}
// ---- DEVELOPER VIEW: where a target price per sq m lands in an area ----
function developerView(stats,target){ // target: {ppsm} or {tier}
  var b=stats.bounds,t=target.tier!=null?target.tier:tierOf(target.ppsm,b);
  if(t<0||!b||!stats.enough)return {ok:false,why:"not enough sales in this area"};
  var tr=stats.tiers[t];
  return {ok:true,tier:t,tierName:TIER_NAMES[t],band:tr.band,shareN:stats.mixN[t],shareValue:stats.mixValue[t],competitors:tr.devs,
    say:stats.mixN[t]+"% of settled sales in "+stats.name+" ("+stats.mixValue[t]+"% of the value) fall in the "+TIER_NAMES[t]+"."+(tr.devs.length?" "+tr.devs.length+" developer"+(tr.devs.length===1?"":"s")+" sit in that tier here.":" No developer with "+EVIDENCE_MIN+"+ sales sits in that tier here.")}}
function compareAreas(a,b,target){return {a:developerView(a,target),b:developerView(b,target)}}
// ---- rent (the same evidence rule; community-level cells, labelled as such) ----
function rentStats(d){var r=d.r||[],n=nOf(r);if(n<EVIDENCE_MIN)return {enough:false,n:n};
  return {enough:true,n:n,rpsm:round(wmedian(pooled(r,1))),rpsf:round(sqftOf(wmedian(pooled(r,1)))),rent:round(wmedian(pooled(r,2)))}}
function rentFit(d,q){var r=(d.r||[]).filter(function(c){return q.beds==null||c[3]===q.beds}),n=nOf(r);
  if(n<EVIDENCE_MIN)return {fit:null,why:"not enough contracts of this size (under "+EVIDENCE_MIN+")",n:n};
  var m=round(wmedian(pooled(r,2)));return {fit:(q.max==null||m<=q.max)&&(q.min==null||m>=q.min),rent:m,rpsf:round(sqftOf(wmedian(pooled(r,1)))),n:n}}
// ---- the whole index ----
// where my developers are: per area, how many of the shortlist have sales on record there
function whereMine(index,set){var o={},s;for(s in index.areas){var a=index.areas[s],c=0,k;for(k in a.devs)if(k!=="_"&&set[k]&&nOf(a.devs[k].c||[])>0)c++;o[s]=c}return o}
// the client meeting, BUYER: for each area, my developers that fit. named = a developer name the client asked for.
function clientMeeting(index,set,q,named){
  var out={areas:[],named:null},bounds=boundsOf(index),s,k;
  for(s in index.areas){var a=index.areas[s],stats=areaStats(a,index),rows=[];
    for(k in a.devs){if(k==="_"||!set[k])continue;var st=devStats({k:k,n:a.devs[k].n,h:a.devs[k].h,c:a.devs[k].c},bounds),bf=budgetFit(a.devs[k],st,q,bounds);if(bf.fit)rows.push({k:k,name:st.name,tier:st.tier,aed:st.aed,median:st.median,medianSqft:st.medianSqft,n:st.n,fitMedian:bf.median,basis:bf.basis})}
    if(rows.length){rows.sort(function(x,y){return x.medianSqft-y.medianSqft});out.areas.push({slug:s,name:a.name,devs:rows})}}
  out.areas.sort(function(x,y){return y.devs.length-x.devs.length});
  if(named){var nk=devKey(named);nk=(index.alias&&index.alias[nk])||nk;out.named={key:nk,mine:!!set[nk],known:!!index.devs[nk],name:(index.devs[nk]||{}).name||named}}
  return out}
function clientMeetingRent(index,set,q){
  var out=[],s,k;for(s in index.areas){var a=index.areas[s],rows=[];
    for(k in a.devs){if(k==="_"||!set[k])continue;var f=rentFit(a.devs[k],q);if(f.fit)rows.push({k:k,name:a.devs[k].n,rent:f.rent,rpsf:f.rpsf,n:f.n})}
    if(rows.length){rows.sort(function(x,y){return x.rent-y.rent});out.push({slug:s,name:a.name,devs:rows})}}
  out.sort(function(x,y){return y.devs.length-x.devs.length});return out}
// ---- v321 - THE DEVELOPER'S BRAND PROFILE: a developer is a brand first, a price in one area second ----
// BRAND TIER = the tier holding most of its PROJECTS (a project = a building with settled sales on record; its tier = that building's median price per sq m).
// A tie goes to the higher tier. If the index carries no project list (an index built before v321), the brand tier falls back to where most of its SALES fall, and says so.
var TIER_WORDS=TIER_NAMES.slice();
var POSITION_WORDS=["Ultra-luxury","Luxury","Premium","Mass-market"];   // a developer's BRAND position (market words), never a price band
var SCALE_PCT=[80,95]; // Boutique = up to the 80th percentile of project counts among developers with SCALE_MIN_SALES or more settled sales; Large-scale = above the 95th (the largest 5 in every 100); Mid-size between
var SCALE_MIN_SALES=100; // small project companies are left out of the percentiles (a developer is still given a word)
function projCount(index,k){var d=index&&index.devs&&index.devs[k];return d&&d.profile&&d.profile.projects>0?d.profile.projects:null}
function scaleCuts(index){var ps=[],k,v;
  for(k in (index&&index.devs)||{}){v=projCount(index,k);if(v>0&&(index.devs[k].n||0)>=SCALE_MIN_SALES)ps.push(v)}
  if(!ps.length)return null;ps.sort(function(a,b){return a-b});
  function q(p){return ps[Math.min(ps.length-1,Math.max(0,Math.ceil(p/100*ps.length)-1))]}
  var lo=q(SCALE_PCT[0]),hi=Math.max(q(SCALE_PCT[1]),lo);
  return {boutiqueMax:lo,midMax:hi,developers:ps.length,lowPct:SCALE_PCT[0],highPct:SCALE_PCT[1]}}
function scaleWord(p,cuts){if(p==null||!cuts)return null;return p<=cuts.boutiqueMax?"Boutique":p<=cuts.midMax?"Mid-size":"Large-scale"}
function scaleSay(cuts){if(!cuts)return "";
  return "Scale words come from the number of projects each of the "+cuts.developers+" developers with "+SCALE_MIN_SALES+" or more settled sales has. Boutique: up to "+cuts.boutiqueMax+" project"+(cuts.boutiqueMax===1?"":"s")+" (the smaller "+cuts.lowPct+" in every 100 developers). Mid-size: "+(cuts.boutiqueMax+1)+" to "+cuts.midMax+". Large-scale: more than "+cuts.midMax+" (the largest "+(100-cuts.highPct)+" in every 100)."}
function pctOf(a){var t=0,i;for(i=0;i<a.length;i++)t+=a[i];return a.map(function(x){return t?Math.round(100*x/t):0})}
function devProfile(index,k,cfg){
  var bounds=boundsOf(index,cfg),dv=(index&&index.devs&&index.devs[k])||null,i,s,t;
  var out={k:k,market:-1,headline:-1,name:dv?dv.name:k,known:!!dv,projects:null,homes:0,areas:0,tierProjects:[0,0,0,0],mixProjects:[0,0,0,0],mixSales:[0,0,0,0],mixValue:[0,0,0,0],brandTier:-1,basis:null,scale:null,cuts:scaleCuts(index),priced:[],thin:[],spread:null,limits:[]};
  var sN=[0,0,0,0],sV=[0,0,0,0],hasB=false,nb=0;
  for(s in (index&&index.areas)||{}){var a=index.areas[s],d=a.devs&&a.devs[k];if(!d)continue;
    var c=d.c||[],n=nOf(c);if(!n)continue;out.areas++;out.homes+=d.h||0;
    for(i=0;i<c.length;i++){t=tierOf(c[i][1],bounds);if(t>=0){sN[t]+=c[i][0];sV[t]+=c[i][0]*(c[i][2]||0)}}
    if(d.b){hasB=true;for(i=0;i<d.b.length;i++){t=tierOf(d.b[i][1],bounds);if(t>=0){out.tierProjects[t]++;nb++}}}
    var st=devStats({k:k,n:out.name,h:d.h,c:c},bounds);
    if(st.enough)out.priced.push({slug:s,name:a.name,n:st.n,medianSqm:st.median,medianSqft:st.medianSqft,tierHere:st.tier});else out.thin.push({slug:s,name:a.name,n:st.n})}
  out.mixSales=pctOf(sN);out.mixValue=pctOf(sV);
  if(hasB&&nb>0){out.projects=nb;out.mixProjects=pctOf(out.tierProjects);out.basis="projects"}
  var src=out.basis==="projects"?out.tierProjects:(out.areas?sN:null),best=-1;
  if(src){best=0;for(i=1;i<4;i++)if(src[i]>src[best])best=i;if(!(src[best]>0))best=-1;if(!out.basis)out.basis="sales"}
  out.brandTier=best;out.scale=scaleWord(out.projects,out.cuts);
  var mv=BRAND_PERCEPTION[k];out.market=mv&&mv.tier>=0?mv.tier:-1;out.headline=out.market;   // a developer class only ever comes from the curated market view, never from price
  out.priced.sort(function(x,y){return y.medianSqm-x.medianSqm});out.thin.sort(function(x,y){return y.n-x.n});
  if(out.priced.length)out.spread={hi:out.priced[0],lo:out.priced[out.priced.length-1],several:out.priced.length>1};
  if(!out.areas)out.limits.push("No sales on the map yet.");
  else{
    if(out.basis==="sales")out.limits.push("Project counts are not in the data yet, so the brand position here is where most of its sales fall.");
    else if(out.projects<3)out.limits.push("Only "+out.projects+" project"+(out.projects===1?"":"s")+" with settled sales on record, so read the brand position as a first look.");
    if(!out.priced.length)out.limits.push("No area has 3 or more settled sales yet, so there is no price to show.");
    else if(out.priced.length===1)out.limits.push("Only one area has 3 or more settled sales, so there is no price range yet.")}
  return out}
function profileSentence(p,unit){if(!p||p.brandTier<0)return p&&!p.areas?p.name+": no sales on the map yet.":"";
  function f(x){return Math.round(unit==="sqm"?x:x/SQFT).toLocaleString("en-US")}var u=unit==="sqm"?"per sq m":"per sq ft",w=TIER_WORDS[p.brandTier].toLowerCase(),a;
  if(p.basis==="projects"){var top=p.tierProjects[p.brandTier];a=p.name+": "+top+" of "+p.projects+" project"+(p.projects===1?"":"s")+(top===1?" sits in the ":" sit in the ")+w}
  else a=p.name+": most of its sales sit in the "+w;
  if(p.spread&&p.spread.several)a+="; prices run from AED "+f(p.spread.lo.medianSqm)+" "+u+" in "+p.spread.lo.name+" to AED "+f(p.spread.hi.medianSqm)+" in "+p.spread.hi.name+".";
  else if(p.spread)a+="; its one priced area is "+p.spread.hi.name+", at AED "+f(p.spread.hi.medianSqm)+" "+u+".";
  else a+="; no area has 3 or more settled sales yet, so there is no price to show.";
  return a}
function brandLabel(t){return t>=0?POSITION_WORDS[t]+" brand":""}
// ---- v321 round 2 ----
// MARKET VIEW: how the trade names a brand. ONE config place; empty except what Kendall stated (4 Oct 2026: nobody will ever call Omniyat premium).
// When a developer is here, its headline brand label is the market view and the data is shown beside it. tier: 0 ultra-luxury, 1 luxury, 2 premium, 3 budget.
var BRAND_PERCEPTION={omniyat:{tier:0,why:"the market always calls Omniyat ultra-luxury"}};
function hasProjects(index){var k;for(k in (index&&index.devs)||{})if(projCount(index,k))return true;return false}
function dataLine(p){if(!p||p.brandTier<0)return "";var i,o=[0,1,2,3].sort(function(a,b){return p.tierProjects[b]-p.tierProjects[a]||a-b}).filter(function(x){return p.tierProjects[x]>0});
  if(p.basis!=="projects")return "most of its sales sit in the "+TIER_WORDS[p.brandTier];
  return o.map(function(x,j){return j===0?p.tierProjects[x]+" of "+p.projects+" project"+(p.projects===1?"":"s")+" in the "+TIER_WORDS[x]:p.tierProjects[x]+" "+TIER_WORDS[x].replace(/ band$/,"")}).join(", ")}
// DRILL-DOWN: the projects (buildings) of one developer sitting in one tier, grouped by area (areaSlug limits it to one area)
function drillProjects(index,k,t,areaSlug,cfg){var bounds=boundsOf(index,cfg),groups=[],s,i;
  for(s in (index&&index.areas)||{}){if(areaSlug&&s!==areaSlug)continue;var a=index.areas[s],d=a.devs&&a.devs[k];if(!d||!d.b||!nOf(d.c||[]))continue;   // v326 - an area where the developer has no sales in the window is not counted by devProfile, so it is not listed either
    var ps=[],tot=0;for(i=0;i<d.b.length;i++){if(tierOf(d.b[i][1],bounds)===t){var pq={name:d.b[i][2]||null,ppsm:d.b[i][1],n:d.b[i][0]};if(d.bx&&d.bx.length===d.b.length&&d.bx[i])pq.ev=d.bx[i];ps.push(pq);tot+=d.b[i][0]}}   // v373 - ev: where the attribution came from (absent in an older index)
    if(ps.length){ps.sort(function(x,y){return y.n-x.n});groups.push({slug:s,name:a.name,projects:ps,n:tot,ppsm:round(wmedian(ps.map(function(p){return [p.ppsm,p.n]})))})}}
  groups.sort(function(x,y){return y.n-x.n});return groups}
// PRICE POSITION: every developer with 3+ settled sales, ranked by its Dubai-wide median price per sq m (the register's last 12 months of sales)
function priceRanking(index){var list=[],k,s;
  for(k in (index&&index.devs)||{}){var cells=[];for(s in index.areas){var d=index.areas[s].devs[k];if(d)cells=cells.concat(d.c||[])}
    if(nOf(cells)>=EVIDENCE_MIN)list.push({k:k,name:index.devs[k].name,ppsm:round(wmedian(pooled(cells,1))),n:nOf(cells)})}
  list.sort(function(a,b){return a.ppsm-b.ppsm||a.k.localeCompare(b.k)});return list}
function mixDist(a,b){var t=0,i;for(i=0;i<4;i++)t+=Math.abs(a[i]-b[i]);return t/2}
var KNOWN_DEVELOPERS=["Omniyat","Nakheel","Meraas","Emaar","Imtiaz","Zaya","Ellington","Select Group","Damac","Mered","Sobha","Binghatti","Arada","Danube","Azizi","Deyaar","Dubai Properties","Union Properties","Aldar","Nshama","Samana","Beyond","Majid Al Futtaim","Dubai Holding","Wasl","Marquis","Object 1"]; // CONFIG: neighbours and peers are named only from this list
function isKnown(k,name){var a=devKey(k.replace(/-/g," ")),b=devKey(name),i;for(i=0;i<KNOWN_DEVELOPERS.length;i++){var n=devKey(KNOWN_DEVELOPERS[i]);if(n&&(n===a||n===b))return true}return false}
var PEER_MIN_SALES=0; // neighbours and peers are named only among developers with this many settled sales or more (3 sales is enough for a price, not for a comparison)
function pricePosition(index,k,ranking){var full=ranking||priceRanking(index),i,at=-1;ranking=full.filter(function(x){return x.k===k||isKnown(x.k,x.name)});
  for(i=0;i<ranking.length;i++)if(ranking[i].k===k)at=i;
  var inFull=false;for(i=0;i<full.length;i++)if(full[i].k===k)inFull=true;
  var out={ranked:inFull,total:full.length,rankedKnown:ranking.length,below:null,above:null,self:at>=0?ranking[at]:null,peers:[],limit:null};
  if(!inFull){var dv=index&&index.devs&&index.devs[k];out.limit=dv?"not enough settled sales (under "+EVIDENCE_MIN+") for a price position":"no sales yet";return out}
  out.below=at>0?ranking[at-1]:null;out.above=at<ranking.length-1?ranking[at+1]:null;
  var me=devProfile(index,k),sc=[];
  for(i=0;i<ranking.length;i++){if(i===at)continue;var o=devProfile(index,ranking[i].k),m1=me.basis==="projects"&&o.basis==="projects",d=mixDist(m1?me.mixProjects:me.mixSales,m1?o.mixProjects:o.mixSales);
    if(me.projects&&o.projects)d+=20*Math.abs(Math.log(me.projects/o.projects)/Math.LN2);
    sc.push({k:ranking[i].k,name:ranking[i].name,ppsm:ranking[i].ppsm,scale:o.scale,projects:o.projects,headline:o.headline,brandTier:o.brandTier,d:d})}
  sc.sort(function(a,b){return a.d-b.d||a.name.localeCompare(b.name)});out.peers=sc.slice(0,3);return out}
// ---- v321 round 3: positioning evidence. Every factor is a number with a plain label; there is NO hidden score. ----
// COASTAL AND PRIME AREAS (district slugs): the one explicit list the location factor uses. Edit here; the page prints it.
var PRIME_AREAS=["palmjumeirah","dubaimarina","dubaimaritimecity","burjkhalifa","alkhairanfirst","palmdeira","alwasl"];
// CURATED QUALITY NOTES (quality, finish, design partners, branded residences are in no register): {developerId:{note:"...",source:"...",date:"..."}}. Shown only when all three are filled.
var QUALITY_NOTES={};
function bandLine(t,bounds,unit){if(!bounds)return "";var lo=t===0?bounds[0]:t===1?bounds[1]:t===2?bounds[2]:null,hi=t===0?null:t===1?bounds[0]:t===2?bounds[1]:bounds[2];
  function f(x){return Math.round(unit==="sqm"?x:x/SQFT).toLocaleString("en-US")}var u=unit==="sqm"?" per sq m":" per sq ft";
  return lo==null?"under AED "+f(hi)+u:hi==null?"AED "+f(lo)+" and above"+u:"AED "+f(lo)+" to "+f(hi)+u}
function devFactors(index,k,cfg){
  var bounds=boundsOf(index,cfg),s,i,cells=[],all=[],out={k:k,priceLevel:null,premium:null,inventory:null,unitMix:null,location:null,delivery:{available:false,why:"the register's planned and actual completion dates are not in this data yet"},quality:null};
  var prof=devProfile(index,k,cfg),premW=0,premS=0,premA=0,prime=0,tot=0,primeNames=[],beds=[0,0,0,0],sizes=[];
  for(s in (index&&index.areas)||{}){var a=index.areas[s],dd=a.devs&&a.devs[k],kk;
    for(kk in a.devs){var cc=a.devs[kk].c||[];all=all.concat(cc)}
    if(!dd)continue;var c=dd.c||[],n=nOf(c);if(!n)continue;cells=cells.concat(c);tot+=n;
    if(PRIME_AREAS.indexOf(s)>=0){prime+=n;primeNames.push(a.name)}
    if(n>=EVIDENCE_MIN){var others=[];for(kk in a.devs)if(kk!==k)others=others.concat(a.devs[kk].c||[]);
      if(nOf(others)>=EVIDENCE_MIN){var r=wmedian(pooled(c,1))/wmedian(pooled(others,1));premW+=n;premS+=n*r;premA++}}}
  var med=nOf(cells)>=EVIDENCE_MIN?wmedian(pooled(cells,1)):null;
  if(med!=null){var dub=wmedian(pooled(all,1)),rnk=priceRanking(index),at=-1;for(i=0;i<rnk.length;i++)if(rnk[i].k===k)at=i;
    out.priceLevel={medianSqm:round(med),medianSqft:round(sqftOf(med)),dubaiSqm:round(dub),dubaiSqft:round(sqftOf(dub)),ratio:med/dub,rank:at+1,total:rnk.length,below:at,pctBelow:rnk.length?Math.round(100*at/rnk.length):null}}
  if(premW>0)out.premium={ratio:premS/premW,areas:premA,sales:premW};
  out.inventory={projects:prof.projects,sales:tot,areas:prof.areas,salesPerProject:prof.projects?Math.round(tot/prof.projects):null,homesPerProject:prof.projects?Math.round(prof.homes/prof.projects):null};
  if(tot>0){for(i=0;i<cells.length;i++){var b=Math.min(cells[i][3],3);beds[b]+=cells[i][0];if(cells[i][1]>0)sizes.push([cells[i][2]/cells[i][1],cells[i][0]])}
    var sm=wmedian(sizes),sb=beds.map(function(x){return Math.round(100*x/tot)});
    out.unitMix={studioOne:null,shares:sb,medianSqm:sm==null?null:round(sm),medianSqft:sm==null?null:round(sm*SQFT)};
    var s01=0;for(i=0;i<cells.length;i++)if(cells[i][3]<=1)s01+=cells[i][0];out.unitMix.studioOne=Math.round(100*s01/tot);
    out.location={primePct:Math.round(100*prime/tot),inlandPct:100-Math.round(100*prime/tot),primeAreas:primeNames,sales:tot}}
  var q=QUALITY_NOTES[k];if(q&&q.note&&q.source&&q.date)out.quality=q;
  return out}
// the position the data suggests, in market words. RULE (stated on the page): the price band holding most of its projects, named Top band = Ultra-luxury, Upper = Luxury, Middle = Premium, Entry = Mass-market.
function suggestedPosition(p){return p&&p.brandTier>=0?p.brandTier:-1}
// TALKING POINT: facts with numbers and a date, the perception only if a market view is set, one open question. No claims about quality, no advice.
function talkingPoint(index,k,unit,cfg){var p=devProfile(index,k,cfg),f=devFactors(index,k,cfg),lines=[],nm=p.name,asof=(index&&index.as_of)||"";
  if(!p.areas||p.brandTier<0){lines.push(nm+": no sales on the map yet.");return {lines:lines,text:lines.join("\n")}}
  var top=0,i;for(i=1;i<4;i++)if(p.mixSales[i]>p.mixSales[top])top=i;
  function fm(x){return Math.round(unit==="sqm"?x:sqftOf(x)).toLocaleString("en-US")}var u=unit==="sqm"?"per sq m":"per sq ft";
  var fact=nm+": "+(p.mixSales[top]>=50?p.mixSales[top]+"% of sales sit in the ":"its largest share of sales ("+p.mixSales[top]+"%) sits in the ")+TIER_WORDS[top]+(f.priceLevel?", median AED "+fm(f.priceLevel.medianSqm)+" "+u:"");
  if(f.premium){var d=Math.round(100*(f.premium.ratio-1));fact+=d===0?", level with the other developers in the same areas":", "+Math.abs(d)+"% "+(d>0?"above":"below")+" the other developers in the same areas"}
  lines.push(fact+(index&&index.window_say?", Dubai Land Department sales register. "+index.window_say.replace(/\.$/,"")+".":", Dubai Land Department sales to "+asof+"."));   // v323 - says which window the figures are from
  if(p.market>=0){lines.push("The market calls it "+POSITION_WORDS[p.market]+"."+(p.market===top?" Its sales sit mostly in the same band.":" Its sales sit mostly in the "+TIER_WORDS[top]+"."))}
  lines.push("When someone calls a developer luxury, is that price per square foot, quality, or who it is built for?");
  return {lines:lines,text:lines.join("\n")}}
// v326 - a saved shortlist can hold ids from before the developer crosswalk ("select", "damac ( )"). Move each to today's id (the index's alias map, then the id itself), drop repeats, keep order.
function resolveSaved(index,ids){var out=[],seen={},al=(index&&index.alias)||{},dv=(index&&index.devs)||{},i,k,c;
  for(i=0;i<(ids||[]).length;i++){k=ids[i];if(typeof k!=="string"||!k)continue;c=dv[k]?k:(al[k]||al[devKey(k)]||k);if(!seen[c]){seen[c]=1;out.push(c)}}
  return out}
// v346 - ONE AREA, TWO SLUGS: althanyahfifth (the Land Department area Al Thanyah Fifth) is Jumeirah Lakes Towers again under another slug (32,616 sales against 32,565, 51 more, and no evidence layer).
// The area is shown once, as jltnorth ("Jumeirah Lakes Towers"); the old slug still RESOLVES to it (links, saved views, PDF requests). jltsouth is NOT an alias: the index names it Jumeirah Islands with its own sales.
var AREA_ALIAS={althanyahfifth:"jltnorth"},AREA_NAMES={jltnorth:"Jumeirah Lakes Towers"};
function resolveArea(slug){var s=String(slug||"").toLowerCase().replace(/[^a-z0-9]/g,"");return AREA_ALIAS[s]||s}
function mergeAreas(index){if(!index||!index.areas)return index;Object.keys(AREA_ALIAS).forEach(function(a){var t=AREA_ALIAS[a];if(index.areas[a]){if(index.areas[t]){delete index.areas[a]}else{index.areas[t]=index.areas[a];delete index.areas[a]}}});Object.keys(AREA_NAMES).forEach(function(t){if(index.areas[t])index.areas[t].name=AREA_NAMES[t]});return index}
// v373 - ATTRIBUTION EVIDENCE (Kendall, 7 Oct 2026: the Land Department register is the authority; a developer's own web site is a claim; every card says where its attribution came from).
// An index built from v373 carries, per developer per area, bx (one evidence record per project of b), ce (one label code per cell of c), and b12x / c12e for the 12-month window
// (labels REGISTER_VERIFIED / NAME_ONLY / DEVELOPER_CLAIMED / UNVERIFIED, codes V N D U). attrSplit keeps ONLY REGISTER_VERIFIED projects and cells in c, b, c12, b12 (so every total, scale word,
// price band and 'where it sells' count is on confirmed projects), moves the rest to index.nconf (shown apart, outside the numbers) and rebuilds index.devs and index.scale.
// An index without these keys is left exactly as it is.
function sourceLine(ev,devName){if(!ev||!ev.e)return "";
  if(ev.e==="REGISTER_VERIFIED")return "Registered developer per DLD register: "+(ev.dn||devName||"");
  if(ev.e==="DEVELOPER_CLAIMED")return ev.dn?"Developer says (website); the register names another developer":"Developer says (website); the register has no record of it";
  if(ev.e==="NAME_ONLY")return "Matched by name only, not confirmed by the register";
  return "Not confirmed"}
function attrSplit(index){if(!index||!index.areas||index.attr&&index.attr.split)return null;
  var has=false,s,k,d;for(s in index.areas){for(k in index.areas[s].devs||{}){d=index.areas[s].devs[k];if(d&&(d.bx||d.b12x)){has=true;break}}if(has)break}
  if(!has)return null;
  var nconf={},hidden=0,kept=0;
  var WIN=[["c","ce","b","bx","all"],["c12","c12e","b12","b12x","l12"]];
  for(s in index.areas){var a=index.areas[s],dels=[];
    for(k in a.devs||{}){d=a.devs[k];if(k==="_")continue;
      WIN.forEach(function(w){var c=d[w[0]],ce=d[w[1]],b=d[w[2]],bx=d[w[3]],i;
        if(Array.isArray(c)&&Array.isArray(ce)&&ce.length===c.length){var nc=[],ne=[];for(i=0;i<c.length;i++)if(ce[i]==="V"){nc.push(c[i]);ne.push("V")}d[w[0]]=nc;d[w[1]]=ne}
        if(Array.isArray(b)&&Array.isArray(bx)&&bx.length===b.length){var nb=[],nx=[];
          for(i=0;i<b.length;i++){if(bx[i]&&bx[i].e==="REGISTER_VERIFIED"){nb.push(b[i]);nx.push(bx[i]);kept++}
            else{hidden++;var o=nconf[k]=nconf[k]||{all:[],l12:[]};o[w[4]].push({slug:s,area:(bx[i]&&bx[i].a)||a.name||s,name:b[i][2]||null,n:b[i][0],ppsm:b[i][1],ev:bx[i]||null})}}
          d[w[2]]=nb;d[w[3]]=nx;
          if(w[4]==="all"){var hs=0,ok=nx.length>0;for(i=0;i<nx.length;i++){if(typeof nx[i].h!=="number"){ok=false;break}hs+=nx[i].h}if(ok||(nx.length===0&&b.length>0))d.h=hs}}});
      if(!(d.c||[]).length&&!(d.c12||[]).length&&!(d.r||[]).length)dels.push(k)}
    dels.forEach(function(k){delete a.devs[k]})}
  // the developer list and the scale cut-offs follow the confirmed projects
  var old=index.devs||{},dl={};
  for(s in index.areas)for(k in index.areas[s].devs){if(k==="_")continue;d=index.areas[s].devs[k];
    var e=dl[k]||(dl[k]={name:(old[k]&&old[k].name)||d.n,areas:0,n:0,profile:{projects:0,homes:0}});
    e.areas++;e.profile.projects+=(d.b||[]).length;e.profile.homes+=d.h||0;(d.c.length?d.c:(d.c12||[])).forEach(function(c){e.n+=c[0]})}
  index.devs=dl;index.scale=scaleCuts({devs:dl});index.nconf=nconf;
  index.attr=index.attr||{};index.attr.split=true;
  return {hidden:hidden,kept:kept,developers:Object.keys(dl).length}}
// the projects of developer k that the register does NOT confirm, for one window ("all" | "l12"): [{slug,area,name,n,ppsm,ev}], biggest first. Empty when the index carries no evidence.
function attrUnconfirmed(index,k,win){var o=index&&index.nconf&&index.nconf[k];if(!o)return [];var l=(o[win==="l12"?"l12":"all"]||[]).slice();l.sort(function(x,y){return y.n-x.n});return l}
// v375 - DELIVERY RECORD for developer k: the register-confirmed developer companies behind its projects (the v373 evidence, REGISTER_VERIFIED, carries the developer id), joined to the delivery file (KV devmap_delay).
// Counts only those companies finished projects that have a planned end date and a completion date; null under 3 such projects, and null when the file or the evidence is absent. History, never a forecast.
function delayRecord(delay,index,k){if(!delay||!delay.by||!index||!index.areas)return null;var ids={},s,d,i,arr,x;for(s in index.areas){d=(index.areas[s].devs||{})[k];if(!d)continue;["bx","b12x"].forEach(function(f){arr=d[f];if(!Array.isArray(arr))return;for(i=0;i<arr.length;i++){x=arr[i];if(x&&x.e==="REGISTER_VERIFIED"&&x.di!=null&&x.di!=="")ids[String(x.di)]=1}})}var n=0,late=0,m=[],names=[],used=0;Object.keys(ids).forEach(function(id){var r=delay.by[id];if(!r||!(r.n>0))return;used++;n+=r.n;late+=r.late||0;(r.m||[]).forEach(function(v){m.push(v)});if(r.name)names.push(r.name)});if(n<(delay.min_projects||3))return null;m.sort(function(a,b){return a-b});var med=m.length?(m.length%2?m[(m.length-1)/2]:(m[m.length/2-1]+m[m.length/2])/2):null;return {n:n,late:late,share:Math.round(100*late/n),median:med==null?null:Math.round(med*10)/10,companies:used,names:names}}
// percentile bounds from a pool of [n,ppsm,...] cells (used by the index builder)
function percentileBounds(cells,percentiles){var p=pooled(cells,1),ps=percentiles||TIER_CFG.percentiles;return ps.map(function(q){return round(wquant(p,q/100))})}
return {AREA_ALIAS:AREA_ALIAS,resolveArea:resolveArea,mergeAreas:mergeAreas,KNOWN_DEVELOPERS:KNOWN_DEVELOPERS,isKnown:isKnown,SCALE_MIN_SALES:SCALE_MIN_SALES,POSITION_WORDS:POSITION_WORDS,PRIME_AREAS:PRIME_AREAS,QUALITY_NOTES:QUALITY_NOTES,bandLine:bandLine,devFactors:devFactors,suggestedPosition:suggestedPosition,talkingPoint:talkingPoint,BRAND_PERCEPTION:BRAND_PERCEPTION,hasProjects:hasProjects,dataLine:dataLine,drillProjects:drillProjects,priceRanking:priceRanking,pricePosition:pricePosition,TIER_WORDS:TIER_WORDS,SCALE_PCT:SCALE_PCT,projCount:projCount,scaleCuts:scaleCuts,scaleWord:scaleWord,scaleSay:scaleSay,devProfile:devProfile,profileSentence:profileSentence,brandLabel:brandLabel,SQFT:SQFT,EVIDENCE_MIN:EVIDENCE_MIN,TIER_IDS:TIER_IDS,TIER_NAMES:TIER_NAMES,TIER_CFG:TIER_CFG,wquant:wquant,wmedian:wmedian,tierOf:tierOf,bandSay:bandSay,devKey:devKey,tierPrices:tierPrices,tierShare:tierShare,TYPICAL_SQFT:TYPICAL_SQFT,devStats:devStats,areaStats:areaStats,shortlistFilter:shortlistFilter,budgetFit:budgetFit,developerView:developerView,compareAreas:compareAreas,rentStats:rentStats,rentFit:rentFit,whereMine:whereMine,clientMeeting:clientMeeting,clientMeetingRent:clientMeetingRent,resolveSaved:resolveSaved,sourceLine:sourceLine,attrSplit:attrSplit,attrUnconfirmed:attrUnconfirmed,delayRecord:delayRecord,percentileBounds:percentileBounds,boundsOf:boundsOf,sqftOf:sqftOf};
})();

export { DM };
